/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.dto.StudentDto;
/**
 *
 * @author User
 */
public class AdminAddStuPanel extends javax.swing.JPanel {
private Controller.AdminStudentController controller;

    /**
     * Creates new form Stusubject
     */
    public AdminAddStuPanel() {
        initComponents();
        // make JTable column
        jstuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"ID", "Name", "Class", "Contact", "Email", "Gender"}
        ));
        
        //  connect Controller
        controller = new Controller.AdminStudentController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jstuTable = new javax.swing.JTable();
        jTxtclass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtCnumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtbirthday = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtpsw = new javax.swing.JTextField();
        jTxtaddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jBtnadd = new javax.swing.JButton();
        jbtndelete = new javax.swing.JButton();
        jbtnupdate = new javax.swing.JButton();
        jbtnreport = new javax.swing.JButton();
        jComboBoxgender = new javax.swing.JComboBox<>();
        jbtnseartch = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jstuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jstuTable);

        jTxtclass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setText("Student ID: ");

        jTxtid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setText("Class: ");

        jTxtCnumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setText("Name: ");

        jTxtname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setText("Contact Number");

        jTxtbirthday.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setText("Email:");

        jTxtemail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setText("Birthday: ");

        jLabel7.setText("Gender: ");

        jLabel8.setText("Password:");

        jTxtpsw.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTxtaddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setText("Address: ");

        jBtnadd.setBackground(new java.awt.Color(51, 255, 51));
        jBtnadd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnadd.setForeground(new java.awt.Color(255, 255, 255));
        jBtnadd.setText("Add");
        jBtnadd.addActionListener(this::jBtnaddActionPerformed);

        jbtndelete.setBackground(new java.awt.Color(255, 0, 0));
        jbtndelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtndelete.setForeground(new java.awt.Color(255, 255, 255));
        jbtndelete.setText("Delete");
        jbtndelete.addActionListener(this::jbtndeleteActionPerformed);

        jbtnupdate.setBackground(new java.awt.Color(255, 255, 0));
        jbtnupdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnupdate.setForeground(new java.awt.Color(255, 255, 255));
        jbtnupdate.setText("Update");
        jbtnupdate.addActionListener(this::jbtnupdateActionPerformed);

        jbtnreport.setBackground(new java.awt.Color(0, 0, 153));
        jbtnreport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnreport.setForeground(new java.awt.Color(255, 255, 255));
        jbtnreport.setText("Get Reoprt");
        jbtnreport.setToolTipText("");
        jbtnreport.addActionListener(this::jbtnreportActionPerformed);

        jComboBoxgender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBoxgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jComboBoxgender.addActionListener(this::jComboBoxgenderActionPerformed);

        jbtnseartch.setBackground(new java.awt.Color(255, 153, 0));
        jbtnseartch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnseartch.setForeground(new java.awt.Color(255, 255, 255));
        jbtnseartch.setText("Seartch by Id");
        jbtnseartch.setToolTipText("");
        jbtnseartch.addActionListener(this::jbtnseartchActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel9)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtid, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxtclass, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTxtname, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jTxtbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addComponent(jLabel7)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxtCnumber)
                                        .addComponent(jComboBoxgender, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jTxtpsw, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTxtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnreport, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jBtnadd)
                        .addGap(18, 18, 18)
                        .addComponent(jbtndelete)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnupdate)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnseartch)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtpsw, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtclass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(36, 36, 36))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTxtbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTxtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTxtCnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jComboBoxgender))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnadd)
                    .addComponent(jbtndelete)
                    .addComponent(jbtnupdate)
                    .addComponent(jbtnseartch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnreport)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnaddActionPerformed
        controller.addStudent();
    }//GEN-LAST:event_jBtnaddActionPerformed

    private void jbtndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndeleteActionPerformed
        controller.deleteStudent();
    }//GEN-LAST:event_jbtndeleteActionPerformed

    private void jbtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnupdateActionPerformed
        controller.updateStudent();
    }//GEN-LAST:event_jbtnupdateActionPerformed

    private void jbtnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnreportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnreportActionPerformed

    private void jComboBoxgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxgenderActionPerformed

    private void jbtnseartchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnseartchActionPerformed
        controller.searchStudent();
    }//GEN-LAST:event_jbtnseartchActionPerformed

public Model.dto.StudentDto getStudentData() {
        return new Model.dto.StudentDto(
            jTxtid.getText(), 
            jTxtname.getText(), 
            jTxtbirthday.getText(), 
            jTxtclass.getText(),
            jTxtCnumber.getText(), 
            jTxtemail.getText(), 
            jTxtaddress.getText(),
            jComboBoxgender.getSelectedItem().toString(), 
            jTxtpsw.getText()
        );
    }

    public void clearFields() {
        jTxtid.setText(""); 
        jTxtname.setText(""); 
        jTxtbirthday.setText("");
        jTxtclass.setText(""); 
        jTxtCnumber.setText(""); 
        jTxtemail.setText("");
        jTxtaddress.setText(""); 
        jTxtpsw.setText("");
    }

    public String getStudentId() {
        return jTxtid.getText();
    }

    public void setStudentData(Model.dto.StudentDto student) {
        jTxtname.setText(student.getName());
        jTxtbirthday.setText(student.getBirthday());
        jTxtclass.setText(student.getStuClass());
        jTxtCnumber.setText(student.getContactNumber());
        jTxtemail.setText(student.getEmail());
        jTxtaddress.setText(student.getAddress());
        jComboBoxgender.setSelectedItem(student.getGender());
        jTxtpsw.setText(student.getPassword());
    }
    
    

    public javax.swing.JTable getTable() {
        return jstuTable;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnadd;
    private javax.swing.JComboBox<String> jComboBoxgender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtCnumber;
    private javax.swing.JTextField jTxtaddress;
    private javax.swing.JTextField jTxtbirthday;
    private javax.swing.JTextField jTxtclass;
    private javax.swing.JTextField jTxtemail;
    private javax.swing.JTextField jTxtid;
    private javax.swing.JTextField jTxtname;
    private javax.swing.JTextField jTxtpsw;
    private javax.swing.JButton jbtndelete;
    private javax.swing.JButton jbtnreport;
    private javax.swing.JButton jbtnseartch;
    private javax.swing.JButton jbtnupdate;
    private javax.swing.JTable jstuTable;
    // End of variables declaration//GEN-END:variables
}
