/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author User
 */
public class DashbordStudent extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashbordStudent.class.getName());

    /**
     * Creates new form DashbordStudent
     */
    public DashbordStudent() {
        initComponents();
        setLocationRelativeTo(null);
        resetMenuColors(); 
        Studashbord studashbord = new Studashbord();
        loadPanel(studashbord);
        
        // 3. ඒ ලෝඩ් වුණු පැනල් එකට අදාළ Label එක විතරක් පාට කිරීම (Active කර පෙන්වීම)
       
        jlbdashbord.setForeground(new java.awt.Color(0, 102, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlbmarks = new javax.swing.JLabel();
        jlbdashbord = new javax.swing.JLabel();
        jlbsubject = new javax.swing.JLabel();
        jlbassigemt = new javax.swing.JLabel();
        jlbedumete = new javax.swing.JLabel();
        jlbprofile = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        sturightpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Dashbord");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 15, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlbmarks.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jlbmarks.setText("My Marks");
        jlbmarks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbmarksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbmarksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbmarksMouseExited(evt);
            }
        });

        jlbdashbord.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jlbdashbord.setText("Dashboard");
        jlbdashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbdashbordMouseClicked(evt);
            }
        });

        jlbsubject.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jlbsubject.setText("My Subject");
        jlbsubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbsubjectMouseClicked(evt);
            }
        });

        jlbassigemt.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jlbassigemt.setText("My Assigement");
        jlbassigemt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbassigemtMouseClicked(evt);
            }
        });

        jlbedumete.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jlbedumete.setText("EduMate");
        jlbedumete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbedumeteMouseClicked(evt);
            }
        });

        jlbprofile.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jlbprofile.setText("Profile");
        jlbprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbprofileMouseClicked(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(255, 51, 51));
        btnlogout.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("Logout");
        btnlogout.addActionListener(this::btnlogoutActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jlbdashbord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbmarks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbassigemt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbedumete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbprofile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jlbsubject, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbdashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbmarks, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbsubject, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbassigemt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbedumete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        sturightpanel.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout sturightpanelLayout = new javax.swing.GroupLayout(sturightpanel);
        sturightpanel.setLayout(sturightpanelLayout);
        sturightpanelLayout.setHorizontalGroup(
            sturightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sturightpanelLayout.setVerticalGroup(
            sturightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sturightpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sturightpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbmarksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbmarksMouseClicked
        resetMenuColors(); 
        // 2. ඊටපස්සේ මේ ක්ලික් කරපු Label එක විතරක් නිල් පාට (හෝ කැමති පාටක්) කරනවා
        jlbmarks.setForeground(new java.awt.Color(0, 102, 255));
        // ViewMyMarks 
        StumarksPanel marksPanel = new StumarksPanel();
        loadPanel(marksPanel);            // TODO add your handling code here:
    }//GEN-LAST:event_jlbmarksMouseClicked

    private void jlbmarksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbmarksMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbmarksMouseEntered

    private void jlbmarksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbmarksMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbmarksMouseExited

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void jlbsubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbsubjectMouseClicked
        // convert all color black
        resetMenuColors(); 
        // 2. change color blue
        jlbsubject.setForeground(new java.awt.Color(0, 102, 255));
        
        Stusubject subjetPanel = new Stusubject();
        loadPanel(subjetPanel);         // TODO add your handling code here:
    }//GEN-LAST:event_jlbsubjectMouseClicked

    private void jlbassigemtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbassigemtMouseClicked
        // convert all color black
        resetMenuColors(); 
        // 2. change color blue
        jlbassigemt.setForeground(new java.awt.Color(0, 102, 255));
        
        Stuassigement assgimentPanel = new Stuassigement();
        loadPanel(assgimentPanel);           // TODO add your handling code here:
    }//GEN-LAST:event_jlbassigemtMouseClicked

    private void jlbedumeteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbedumeteMouseClicked
         // convert all color black
        resetMenuColors(); 
        // 2. change color blue
        jlbedumete.setForeground(new java.awt.Color(0, 102, 255));
        
       Edumate edumate = new Edumate();
        loadPanel(edumate);      
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbedumeteMouseClicked

    private void jlbprofileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbprofileMouseClicked
            // convert all color black
        resetMenuColors(); 
        // 2. change color blue
        jlbprofile.setForeground(new java.awt.Color(0, 102, 255));
        
        Stuprofile stuprofile = new Stuprofile();
        loadPanel(stuprofile);          // TODO add your handling code here:
    }//GEN-LAST:event_jlbprofileMouseClicked

    private void jlbdashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbdashbordMouseClicked
        resetMenuColors(); 
        Studashbord studashbord = new Studashbord();
        loadPanel(studashbord);
        
        // 3. ඒ ලෝඩ් වුණු පැනල් එකට අදාළ Label එක විතරක් පාට කිරීම (Active කර පෙන්වීම)
      
        jlbdashbord.setForeground(new java.awt.Color(0, 102, 255));       
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbdashbordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashbordStudent().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlbassigemt;
    private javax.swing.JLabel jlbdashbord;
    private javax.swing.JLabel jlbedumete;
    private javax.swing.JLabel jlbmarks;
    private javax.swing.JLabel jlbprofile;
    private javax.swing.JLabel jlbsubject;
    private javax.swing.JPanel sturightpanel;
    // End of variables declaration//GEN-END:variables


// Method to load a new panel into the rightPanel
    public void loadPanel(javax.swing.JPanel panel) {
        sturightpanel.removeAll(); // Remove all existing components from the panel
        sturightpanel.setLayout(new java.awt.BorderLayout()); // Set layout to fill the entire space
        sturightpanel.add(panel); // Add the new panel
        sturightpanel.revalidate(); // Revalidate the UI to apply changes
        sturightpanel.repaint(); // Repaint the UI to show the new panel
    }
    
    // සියලුම Menu Labels වල පාට සාමාන්‍ය (කලු) කිරීම සඳහා
    private void resetMenuColors() {
        // ඔයාගේ අකුරු වල මුල් පාට මෙතැනට දෙන්න (උදා: කලු නම් 0, 0, 0)
        java.awt.Color defaultColor = new java.awt.Color(0, 0, 0); 
        jlbdashbord.setForeground(defaultColor);
        jlbmarks.setForeground(defaultColor);
        jlbsubject.setForeground(defaultColor);
        jlbassigemt.setForeground(defaultColor);
        jlbedumete.setForeground(defaultColor);
        jlbprofile.setForeground(defaultColor);
    }
}
