/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author User
 */
public class DashbordAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashbordAdmin.class.getName());

    /**
     * Creates new form DashbordStudent
     */
    public DashbordAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        resetMenuColors(); 
       StumarksPanel marksPanel = new StumarksPanel();
        loadPanel(marksPanel); 
        
      
       
        jlbdashbord.setForeground(new java.awt.Color(0, 102, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlbadmin = new javax.swing.JLabel();
        jlbdashbord = new javax.swing.JLabel();
        jlbstudent = new javax.swing.JLabel();
        jlbsubject = new javax.swing.JLabel();
        jlbpayment = new javax.swing.JLabel();
        jlbprofile = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jlbteacher = new javax.swing.JLabel();
        jlbclass = new javax.swing.JLabel();
        sturightpanel = new javax.swing.JPanel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Dashbord");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 15, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlbadmin.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jlbadmin.setText("Add Admin");
        jlbadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbadminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbadminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbadminMouseExited(evt);
            }
        });

        jlbdashbord.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jlbdashbord.setText("Dashboard");
        jlbdashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbdashbordMouseClicked(evt);
            }
        });

        jlbstudent.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jlbstudent.setText("Add Student");
        jlbstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbstudentMouseClicked(evt);
            }
        });

        jlbsubject.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jlbsubject.setText("Add Subject");
        jlbsubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbsubjectMouseClicked(evt);
            }
        });

        jlbpayment.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jlbpayment.setText("Payments");
        jlbpayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbpaymentMouseClicked(evt);
            }
        });

        jlbprofile.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jlbprofile.setText("Profile");
        jlbprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbprofileMouseClicked(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(255, 51, 51));
        btnlogout.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("Logout");
        btnlogout.addActionListener(this::btnlogoutActionPerformed);

        jlbteacher.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jlbteacher.setText("Add Teacher");
        jlbteacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbteacherMouseClicked(evt);
            }
        });

        jlbclass.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jlbclass.setText("Add Class");
        jlbclass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbclassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlbteacher, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jlbdashbord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbsubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbpayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbprofile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbclass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlbdashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbteacher, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbsubject, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbclass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        sturightpanel.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout sturightpanelLayout = new javax.swing.GroupLayout(sturightpanel);
        sturightpanel.setLayout(sturightpanelLayout);
        sturightpanelLayout.setHorizontalGroup(
            sturightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sturightpanelLayout.setVerticalGroup(
            sturightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sturightpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sturightpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbadminMouseClicked
        resetMenuColors(); 
        // 2. ඊටපස්සේ මේ ක්ලික් කරපු Label එක විතරක් නිල් පාට (හෝ කැමති පාටක්) කරනවා
        jlbadmin.setForeground(new java.awt.Color(0, 102, 255));
        // ViewMyMarks 
        StumarksPanel marksPanel = new StumarksPanel();
        loadPanel(marksPanel);            
    }//GEN-LAST:event_jlbadminMouseClicked

    private void jlbadminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbadminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbadminMouseEntered

    private void jlbadminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbadminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbadminMouseExited

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
          int choice = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to logout?", 
                "Logout Confirmation", 
                javax.swing.JOptionPane.YES_NO_OPTION);

        
        if (choice == javax.swing.JOptionPane.YES_OPTION) {
            //  Dashboard
            this.dispose(); 
            // Startview ( Login)
            View.Startview startPage = new View.Startview();
            startPage.setVisible(true);
        }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void jlbstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbstudentMouseClicked
        // convert all color black
        resetMenuColors(); 
        // 2. change color blue
        jlbstudent.setForeground(new java.awt.Color(0, 102, 255));
        
        AdminAddStuPanel addStuPanel = new AdminAddStuPanel();
       loadPanel(addStuPanel);       
    }//GEN-LAST:event_jlbstudentMouseClicked

    private void jlbsubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbsubjectMouseClicked
        // convert all color black
        resetMenuColors(); 
        // 2. change color blue
        jlbsubject.setForeground(new java.awt.Color(0, 102, 255));
        
        Stuassigement assgimentPanel = new Stuassigement();
        loadPanel(assgimentPanel);          
    }//GEN-LAST:event_jlbsubjectMouseClicked

    private void jlbpaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbpaymentMouseClicked
         // convert all color black
        resetMenuColors(); 
        // 2. change color blue
        jlbpayment.setForeground(new java.awt.Color(0, 102, 255));
        
       Edumate edumate = new Edumate();
        loadPanel(edumate);      
        
    }//GEN-LAST:event_jlbpaymentMouseClicked

    private void jlbprofileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbprofileMouseClicked
            // convert all color black
        resetMenuColors(); 
        // 2. change color blue
        jlbprofile.setForeground(new java.awt.Color(0, 102, 255));
        
        Stuprofile stuprofile = new Stuprofile();
        loadPanel(stuprofile);       
    }//GEN-LAST:event_jlbprofileMouseClicked

    private void jlbdashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbdashbordMouseClicked
        resetMenuColors(); 
        AdminAddStuPanel addStuPanel = new AdminAddStuPanel();
        loadPanel(addStuPanel);
        
        // change menu color
      
        jlbdashbord.setForeground(new java.awt.Color(0, 102, 255));       
        
    }//GEN-LAST:event_jlbdashbordMouseClicked

    private void jlbteacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbteacherMouseClicked
        // convert all color black
        resetMenuColors(); 
        // 2. change color blue
        jlbteacher.setForeground(new java.awt.Color(0, 102, 255));        
    }//GEN-LAST:event_jlbteacherMouseClicked

    private void jlbclassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbclassMouseClicked
        resetMenuColors(); 
        // 2. change color blue
        jlbclass.setForeground(new java.awt.Color(0, 102, 255));
    }//GEN-LAST:event_jlbclassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashbordAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogout;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlbadmin;
    private javax.swing.JLabel jlbclass;
    private javax.swing.JLabel jlbdashbord;
    private javax.swing.JLabel jlbpayment;
    private javax.swing.JLabel jlbprofile;
    private javax.swing.JLabel jlbstudent;
    private javax.swing.JLabel jlbsubject;
    private javax.swing.JLabel jlbteacher;
    private javax.swing.JPanel sturightpanel;
    // End of variables declaration//GEN-END:variables


// Method to load a new panel into the rightPanel
    public void loadPanel(javax.swing.JPanel panel) {
        sturightpanel.removeAll(); // Remove all existing components from the panel
        sturightpanel.setLayout(new java.awt.BorderLayout()); // Set layout to fill the entire space
        sturightpanel.add(panel); // Add the new panel
        sturightpanel.revalidate(); // Revalidate the UI to apply changes
        sturightpanel.repaint(); // Repaint the UI to show the new panel
    }
    
    // සියලුම Menu Labels වල පාට සාමාන්‍ය (කලු) කිරීම සඳහා
    private void resetMenuColors() {
        // ඔයාගේ අකුරු වල මුල් පාට මෙතැනට දෙන්න (උදා: කලු නම් 0, 0, 0)
        java.awt.Color defaultColor = new java.awt.Color(0, 0, 0); 
        jlbdashbord.setForeground(defaultColor);
        jlbadmin.setForeground(defaultColor);
        jlbstudent.setForeground(defaultColor);
        jlbsubject.setForeground(defaultColor);
        jlbpayment.setForeground(defaultColor);
        jlbprofile.setForeground(defaultColor);
        jlbclass.setForeground(defaultColor);
        jlbteacher.setForeground(defaultColor);
    }
}
