/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AdminLoginController;

/**
 *
 * @author User
 */
public class Loginviewadmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Loginviewadmin.class.getName());

    /**
     * Creates new form Loginview
     */
    public Loginviewadmin() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        adminpsw = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        adminemail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/school logo.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel3.setText("Admin Login");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        btnlogin.setBackground(new java.awt.Color(0, 204, 51));
        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("Loging");
        btnlogin.addActionListener(this::btnloginActionPerformed);
        jPanel1.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        btnback.setBackground(new java.awt.Color(51, 0, 153));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addActionListener(this::btnbackActionPerformed);
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        adminpsw.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminpsw.setForeground(new java.awt.Color(0, 0, 51));
        adminpsw.addActionListener(this::adminpswActionPerformed);
        jPanel1.add(adminpsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 215, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 166, -1));

        adminemail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminemail.setForeground(new java.awt.Color(0, 0, 51));
        adminemail.addActionListener(this::adminemailActionPerformed);
        jPanel1.add(adminemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 215, 28));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Email");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 166, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 340, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminemailActionPerformed

    private void adminpswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminpswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminpswActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
            try {
            // 1. Get input Text Fields Email, Password 
            String email = adminemail.getText();
            String password = adminpsw.getText();

            // 2. DTO 
            Model.dto.AdminLoginDto loginDTO = new Model.dto.AdminLoginDto(email, password);
            
            // 3. ඔබ සෑදූ DAO එක හරහා ඩේටාබේස් එක චෙක් කිරීම
            Model.dao.AdminAuthDAO dao = new Model.dao.AdminAuthDAO();
            Model.entity.AdminEntity admin = dao.loginAdmin(loginDTO);

            // 4. දත්ත නිවැරදි නම් (Database එකෙන් ඇඩ්මින්ගේ විස්තර ආවා නම්)
            if (admin != null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Welcome Admin, " + admin.getName() + "!");
                
                // Login 
                this.dispose(); 
                
                // Admin Dashboard ( Admin Dashboard)
                View.DashbordAdmin dash = new View.DashbordAdmin();
                dash.setVisible(true); 
                
            } else {
               
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid Email or Password!", "Login Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
                int choice = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to back?", 
                "back Confirmation", 
                javax.swing.JOptionPane.YES_NO_OPTION);

        
        if (choice == javax.swing.JOptionPane.YES_OPTION) {
            
            //  Dashboard
            this.dispose(); 
            // Startview ( Login)
            View.Startview startPage = new View.Startview();
            startPage.setVisible(true);
        }  
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Loginviewadmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminemail;
    private javax.swing.JTextField adminpsw;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public String getEmail() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public String getPassword() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   public void addLoginListener(java.awt.event.ActionListener listener) {
        btnlogin.addActionListener(listener); 
    }
}
