/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author User
 */
public class Startview extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Startview.class.getName());

    /**
     * Creates new form startview
     */
    public Startview() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStudent = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JButton();
        btnTeacher = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnhelp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        startimgbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStudent.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/student.jpg"))); // NOI18N
        btnStudent.addActionListener(this::btnStudentActionPerformed);
        getContentPane().add(btnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 160, 170));

        jLabel3.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Central College Anuradhapura");
        jLabel3.setAutoscrolls(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, 90));

        btnAdmin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/admin.jpg"))); // NOI18N
        btnAdmin.addActionListener(this::btnAdminActionPerformed);
        getContentPane().add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 160, 170));

        btnTeacher.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnTeacher.setForeground(new java.awt.Color(255, 255, 255));
        btnTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/teacher.jpeg"))); // NOI18N
        btnTeacher.addActionListener(this::btnTeacherActionPerformed);
        getContentPane().add(btnTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 160, 170));

        jLabel1.setText("Date / time");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        btnhelp.setFont(new java.awt.Font("Perpetua", 0, 12)); // NOI18N
        btnhelp.setForeground(new java.awt.Color(0, 0, 102));
        btnhelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/help-desk (1).png"))); // NOI18N
        btnhelp.setText("HELP");
        btnhelp.addActionListener(this::btnhelpActionPerformed);
        getContentPane().add(btnhelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Student");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Admin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Teacher");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        startimgbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/startbg.jpg"))); // NOI18N
        getContentPane().add(startimgbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -100, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
             java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View.Loginviewstudent().setVisible(true);
                
            }
        }); 
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View.Loginviewadmin().setVisible(true);
            }
        });     
       this.dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View.Loginviewteacher().setVisible(true);
            }
        });      
        this.dispose();
    }//GEN-LAST:event_btnTeacherActionPerformed

    private void btnhelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Startview().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton btnTeacher;
    private javax.swing.JButton btnhelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel startimgbg;
    // End of variables declaration//GEN-END:variables
}
